### ISSUE TITLE
no work D:

### ISSUE THREAD

**Issue by lunarskid** [geode-sdk/sdk#31]
camila catgirl <3

![image](https://user-images.githubusercontent.com/59777379/170065031-bd3031df-7b57-4709-931d-34dd04548b1b.png)
dedicated to cvolton

im lunar and this is my biography

![image](https://user-images.githubusercontent.com/59777379/170065256-4d8bf0f7-55e5-4712-90f5-9f2188db4ca1.png)

ily sm camila and u dice ur the best mom anyways heres the error

this shiddy sdk wont fucking work >:(
it uses erm rust and crashes so much, cant install

i believe in u devs especially u camila :3
pleas fix for catgirl pics owo 

kthxbai

**Comment by HJfod** [comment]
pool's closed due to stingrays with aids

**Comment by lunarskid** [comment]
what the fuck lmao
