### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by camila314** [geode-sdk/sdk#9]
discord has completely stopped working for me but I wasn't done arguing about dumb stuff can we continue here

**Comment by camila314** [comment]
@poweredbypie @HJfod pls

**Comment by poweredbypie** [comment]
dude im not going to argue in a fucking github issue

also i still dont like macros literally
```cpp
Geode::custom_entry = [](Mod* mod) -> void {

}
```

is not more verbose than
```cpp
void $entry(Mod* mod) {

}
```

and to be honest, i think it hides less information from the user (this is coming from someone that always uses `this->` in front of members

**Comment by camila314** [comment]
first one's perfectly good by me, i just didn't like the extra assignment of the other idea or the mandatory entrypoint.
