### ISSUE TITLE
libcocos2d.dll EXCEPTION_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by DelofJ** [geode-sdk/sdk#928]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v3.0.0-beta.2

### Mods Installed

In the crash report

### Steps to Reproduce

1) I opened the game
2) I checked some mods
3) I updated 2 mods
4) I got back to the main menu and went to my saved levels
5) It randomly crashed

### Crash Report

[2024-06-20_02-02-53.log](https://github.com/user-attachments/files/15906847/2024-06-20_02-02-53.log)

**Comment by hiimjustin000** [comment]
I experienced this crash too, it's fixed in [this version](https://github.com/geode-sdk/geode/actions/runs/9588516584/artifacts/1618592597)

**Comment by hiimjustin000** [comment]
Yes.
